private_task: cifar10
public_task: cifar100
server_model: resnet20
client_model: resnet20
partition: client_inner_dirichlet
dir_alpha: 0.3
seed: 42
public_size: 10000
public_size_per_round: 1000
# Support only for SCARLET
validation_ratio: 0.0
sample_ratio: 1.0
global_round: 2000
num_clients: 100
batch_size: 100
epochs: 5
lr: 0.1
kd_epochs: 5
kd_batch_size: 100
kd_lr: 0.1
test_batch_size: 500
server_test_batch_size: 1000
num_parallels: 10
comment: ""
data_dir: "./data"
